# Generated by Django 5.2.10 on 2026-07-17 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_conversationcontextmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatWidgetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_widget_settings',
            },
        ),
        migrations.RenameIndex(
            model_name='conversationcontextmodel',
            new_name='chat_conver_convers_a59d92_idx',
            old_name='chat_conver_convers_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationcontextmodel',
            new_name='chat_conver_updated_464a0c_idx',
            old_name='chat_conver_updated_d4e5f6_idx',
        ),
        migrations.AddField(
            model_name='chatwidgetsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
