"""
Django settings for centene_forecast_project project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize django-environ
env = environ.Env(
    # Set default values and casting
    DEBUG=(bool, False),
    OPENAI_API_KEY=(str, ''),
)

# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h0t!93%i^&wu1a08%)-t^=-1qqowl)l45&b-x2r#lj&v-y-&n4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be FIRST for WebSocket support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # my django apps
    'core', # for models and backends
    'centene_forecast_app',
    'chat_app',  # Chat interface with WebSocket
    # external apps
    'channels',  # WebSocket support
    'django_q',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # whitenoise middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # custom middlewares
    'middleware.fallback_middleware.PermissionFallbackMiddleware',
]

ROOT_URLCONF = 'centene_forecast_project.urls'

LDAP_AUTH_URL = "ldap://americas.global.nttdata.com"
AUTHENTICATION_BACKENDS = [
    'core.backends.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]
# AUTH_USER_MODEL='auth.User'
AUTH_USER_MODEL = 'core.User'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'centene_forecast_app.context_processors.combined_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'centene_forecast_project.wsgi.application'
ASGI_APPLICATION = 'centene_forecast_project.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

    # "default": {
    #     "ENGINE": "mssql",
    #     "NAME": "centene_forecast",
    #     "USER": "user",
    #     "PASSWORD": "pass",
    #     "HOST": "localhost",
    #     "PORT": "1433",
    #     "OPTIONS": {"driver": "ODBC Driver 17 for SQL Server",
    #     'trusted_connection':'yes',
    #     },
    # },
}

# =============================================================================
# CACHE CONFIGURATION
# =============================================================================
CACHE_DIR = os.path.join(BASE_DIR, 'cache_files')
os.makedirs(CACHE_DIR, exist_ok=True)


CACHES = {
    # primary cache: Fast local memory cache for single worker
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'forecast-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    },
    # secondary cache: File based cache for multiple workers
    'filebased': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': CACHE_DIR,
        'OPTIONS': {
            'MAX_ENTRIES': 10000
        }
    },

}

LOGIN_URL = 'forecast_app:login'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/Centene-app/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # Ensure BASE_DIR is defined at the top of settings.py
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Background Task (Django-Q)

Q_CLUSTER = {
    "name": "DjangoQ",
    "workers": 4,
    "timeout": 60,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
}

API_BASE_URL = "http://127.0.0.1:8888"

PBIRS_CLAIMS_CAPACITY_URL = (
    "http://10.111.36.98/reports/powerbi/COMMERCIAL/Centene/"
    "Claims%20Capacity%20Planning%20Dashboard?rs:Embed=true"
)

# =============================================================================
# CHANNEL LAYERS CONFIGURATION (WebSocket Support)
# =============================================================================
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
        "CONFIG": {
            "capacity": 100,
            "expiry": 60,
        }
    },
}

# =============================================================================
# CHAT CONFIGURATION
# =============================================================================
CHAT_CONFIG = {
    'enabled': True,
    'mock_mode': True,  # Set to False to use real LLM (Phase 2)
    'max_conversation_history': 50,
    'rate_limit_messages_per_minute': 10,
}

# LLM Configuration (for Phase 2+ when integrating real LLM)
LLM_CONFIG = {
    'provider': 'openai',
    'model': 'gpt-4-turbo-preview',
    'api_key': env('OPENAI_API_KEY'),  # Read from .env file
    'max_tokens': 4096,
    'temperature': 0.1,
    'use_langchain': True,
}

# =============================================================================
# LLM WORKFLOW LOGGING CONFIGURATION
# =============================================================================
LLM_LOGGING_CONFIG = {
    'enabled': True,
    'log_level': 'DEBUG' if DEBUG else 'INFO',
    'log_full_prompts': DEBUG,      # Full prompts only in dev
    'log_full_responses': DEBUG,    # Full responses only in dev
    'max_preview_length': 500,      # Truncate in production
    'redact_api_keys': True,
    'redact_user_pii': not DEBUG,
}


from datetime import datetime
from logging.handlers import RotatingFileHandler

# Global variable to track the current file number
current_file_number = 1
current_date = datetime.now().date()

# Base directory for logs
LOG_DIR = os.path.join(BASE_DIR.parent, 'logs')

# Ensure the log directory exists
os.makedirs(LOG_DIR, exist_ok=True)

# Function to generate the log file name based on the current date and file number
def get_log_file_name(file_number):
    today_str = datetime.now().strftime("%Y%m%d")
    date = datetime.now().date()

    date_directory = os.path.join(LOG_DIR, str(date))

    # Ensure the date-specific log directory exists
    os.makedirs(date_directory, exist_ok=True)

    return os.path.join(date_directory, f"log{today_str}_{file_number}.log")


# Function to generate LLM workflow log file name
def get_llm_log_file_name():
    today_str = datetime.now().strftime("%Y%m%d")
    date = datetime.now().date()

    date_directory = os.path.join(LOG_DIR, str(date))

    # Ensure the date-specific log directory exists
    os.makedirs(date_directory, exist_ok=True)

    return os.path.join(date_directory, f"llm_workflow_{today_str}.log")

# Setting the maximum size for log files
MAX_LOG_SIZE = 5 * 1024 * 1024  # 5MB
BACKUP_COUNT = 5  # Number of backup logs to keep

class CustomRotatingFileHandler(RotatingFileHandler):
    def doRollover(self):
        global current_file_number, current_date


        # Check if the date has changed
        new_date = datetime.now().date()
        if new_date != current_date:
            # Reset file number and update the current date
            current_file_number = 1
            current_date = new_date
            # # Ensure the directory for the new date exists
            # new_log_directory = os.path.join(LOG_DIR, str(new_date))
            # os.makedirs(new_log_directory, exist_ok=True)

        else:
            # Increment file number if it's the same day
            current_file_number += 1

        # Set the new logging filename
        self.baseFilename = get_log_file_name(current_file_number)
        # self.stream = self._open()  # Open the new file stream
        # Perform the standard rollover
        super().doRollover()

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            '()': 'chat_app.utils.llm_logger.LLMLogFormatter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'INFO',
        },
        'file': {
            'class': f'{__name__}.CustomRotatingFileHandler',
            'level': 'DEBUG',
            'formatter': 'verbose',
            'filename': get_log_file_name(current_file_number),  # Use the initial file name
            'maxBytes': MAX_LOG_SIZE,
            'encoding': 'utf-8',  # Fix Unicode encoding issues
            # 'backupCount': BACKUP_COUNT,
        },
        'llm_file': {
            'class': f'{__name__}.CustomRotatingFileHandler',
            'level': 'DEBUG',
            'formatter': 'json',
            'filename': get_llm_log_file_name(),
            'maxBytes': MAX_LOG_SIZE,
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'llm_workflow': {
            'handlers': ['console', 'llm_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'llm_workflow.intent': {
            'handlers': ['console', 'llm_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'llm_workflow.parameters': {
            'handlers': ['console', 'llm_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'llm_workflow.validation': {
            'handlers': ['console', 'llm_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'llm_workflow.query': {
            'handlers': ['console', 'llm_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'llm_workflow.error': {
            'handlers': ['console', 'llm_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# =============================================================================
# DEVELOPMENT SSL CONFIGURATION
# =============================================================================
# Disable SSL verification for development (corporate SSL inspection workaround)
# WARNING: Only runs when DEBUG=True. Never use in production!
if DEBUG:
    try:
        from dev_ssl_config import configure_dev_ssl
        configure_dev_ssl()
    except ImportError:
        pass
