# Generated by Django 5.0.14 on 2025-07-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_data',
            field=models.BinaryField(),
        ),
    ]
